---
title: "CCA `CompEcon` Replication Project"
subtitle: "Replication of The Political Legacy of Entertainment TV by Durante, Pinotti and Tesei (AER, 2019)"
author: 
  - name: Francesco Checola
    orcid: 0009-0008-8503-1530
    email: francesco.checola@unito.it
    affiliations: University of Turin, Collegio Carlo Alberto
---


::: {.callout-note}

# Collegio Carlo Alberto Replication Project

This report was created as part of the assessment for the [`Computational Economics` Course](https://floswald.github.io/CompEcon/) in the PhD program at Collegio Carlo Alberto taught by [Florian Oswald](https://floswald.github.io/).

:::

> {REPLICATOR} Every line which looks like this one, that is, it starts with {REPLICATOR} and has this formatting (there is a grey bar on the left 👀), is an **instruction for you, the replicator**. When you are done with editing this file, _there should be no such line left_ - you should delete all of them.

## Paper and Replication Package

This report presents a replication of the empirical results in:

- Durante, R., Pinotti, P., and Tesei, A. (2019). *The Political Legacy of Entertainment TV*. American Economic Review, 109(7), 2497–2530. https://doi.org/10.1257/aer.20150958

- Durante, R., Pinotti, P., and Tesei, A. (2019). *Replication data for: The Political Legacy of Entertainment TV*. American Economic Association [publisher], distributed by ICPSR. https://doi.org/10.3886/E116167V1

The analysis is conducted using the `Julia` programming language.

We aim to replicate the following exhibits:

1. Figure 4 – Mediaset Signal Strength (1985)
2. Table 1 – Balance Tests: Exposure to Mediaset and Voting for Italian Main Parties (1972–1992)
3. Table 2 – Balance Tests: Exposure to Mediaset and Municipality Characteristics
4. Table 3 – Main Results: Exposure to Mediaset and Voting for Forza Italia (1994)
5. Table 4 – Robustness: Exposure to Mediaset and Voting for Forza Italia (1994)
6. Figure 5 – Robustness: Exposure to Mediaset and Voting for Forza Italia (1994)
7. Table 5 – Exposure to Mediaset and Voting for Italian Main Parties (1994–2022) *(extension)*
8. Table 6 – Exposure to Mediaset and Political Attitudes *(optional)*
9. Table 10 – Exposure to Mediaset and Opinions about Berlusconi *(optional)*

> {REPLICATOR}: leave comments here for partial results, caveats, and other observations


## High Level Description of Computational Problem in Paper

> {REPLICATOR}: please write here a concise summary describing the main computational tasks in this paper, i.e. which equations to solve, which to estimate, which methodology, any implementation details visible from the replication package (algorithms, packages, procedures used)
>
> You can use standard $\LaTeX$ expression, $x+y$, also display mode of course 
> $$\begin{align}
> x +y & = z\\
> z &= 0
> \end{align}$$


## Computational Requirements

Here are the original package's computational requirements:

- [ ] No requirements specified
- [ ] Software Requirements specified as follows:
  - Software 1, version ...
  - Software 2, version ...
- [ ] Computational Requirements specified as follows:
  - Cluster size, etc.
- [ ] Time Requirements specified as follows:
  - Length of necessary computation (hours, weeks, etc.)


## Our Computational setup

> {REPLICATOR}: please fill in manually. Remove examples that are not relevant, adjust examples to fit special circumstances. Some of this is available from the standard log output in Stata or R. Some frequently used details are below. Some of these details can be found as follows:
>
> - (Windows) by right-clicking on "This PC"
> - (Mac) Apple-menu > "About this Mac"
> - (Linux) see code in `tools/linux-system-info.sh`
>
> Some options are listed below. Choose the one that applies and delete everything else.

- Mac Laptop M2 MacBook Pro, MacOS 10.14.6, 8 GB of memory, (M2 Processor, 8 cores)
- RedCloud Servers: Intel Xeon Processor (Skylake) 3.09 GHz (18 processors), Installed Ram 176 GB, 64-bit operating system, x64-based processor
- CCSS Cloud: Windows Server AMD EPYC 7763 64-Core Processor 2.44 GHz, 128GB
- BioHPC Linux server, Rocky Linux 9.0, AMD Opteron Processor 6380 / 16 cores/ 125 GB memory (adjust as necessary from output of linux-system-info.sh)
- WholeTale (describe the environment chosen)
- CodeOcean (describe the type of capsule chosen) Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (16 cores), 128 GB Memory
- Bitbucket Pipelines, "Ubuntu 20.04.2 LTS", Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz, 8 cores, 9GB memory
- Codespaces, "Ubuntu 20.04.2 LTS", Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz, 2 core, 8GB/ 4-core, 16GB/ 8-core, 32 GB/ 16-core, 64GB (choose appropriately)


> {REPLICATOR}: Please also list the software you used (specific versions). List only the ones you used, add any not listed in the examples:

- Stata/MP 18.0
- Matlab R2022a
- Intel Compiler 3.14152 (note: there is no such thing, so please verify the version!)



# Replication

## Figure 4 – Mediaset Signal Strength (1985)

This figure replicates the geographical distribution of Mediaset signal strength across Italian municipalities in 1985.

Panel A shows predicted signal strength, while Panel B reports signal strength in free space, excluding geographical obstacles.

Work in progress: data cleaning and geographical mapping.

```{julia}
using StatFiles, DataFrames

df = DataFrame(load("replication-package/data/raw/municipality-level_data.dta"))

display(first(df, 5))
display(names(df))
```

```{julia}
using GeoDataFrames

municipalities = GeoDataFrames.read("replication-package/data/raw/Com01012013/Com01012013_WGS84.shp")

display(first(municipalities, 5))
display(names(municipalities))
```

```{julia}
using DataFrames, Plots

df_unique = unique(df, :istat)

df_unique = filter(row -> !ismissing(row.istat), df_unique)
df_unique.istat = Int.(df_unique.istat)

df_map = leftjoin(municipalities, df_unique, on = :PRO_COM => :istat)

df_map = filter(row ->
    !ismissing(row.signal_nonstand) &&
    !ismissing(row.signalfree_nonstand),
    df_map
)

p1 = plot(df_map, color = :signal_nonstand, legend = false,
    title = "Panel A. Predicted signal strength")

p2 = plot(df_map, color = :signalfree_nonstand, legend = false,
    title = "Panel B. Signal strength in free space")

plot(p1, p2, layout = (1, 2), size = (1000, 450))
```